export default [
  {
    id: 1,
    name: "Water plants",
    money: 0.25,
    permanent: true,
    repeatable: false,
    urgent: false,
  },
  {
    id: 2,
    name: "Make bed",
    money: 0.25,
    permanent: true,
    repeatable: false,
    urgent: false,
  },
  {
    id: 3,
    name: "Pick prescription up",
    money: 0.5,
    permanent: false,
    repeatable: false,
    urgent: false,
  },
  {
    id: 4,
    name: "Complete work presentation",
    money: 3,
    permanent: false,
    repeatable: false,
    urgent: true,
  },
  {
    id: 5,
    name: "Read one chapter",
    money: 0.5,
    permanent: true,
    repeatable: true,
    urgent: false,
  },
  {
    id: 6,
    name: "Call Ali",
    money: 1,
    permanent: false,
    repeatable: false,
    urgent: false,
  },
];
