export default [
  {
    id: 1,
    name: "Water plants",
    money: 0.25,
    permanent: true,
    repeatable: false,
    urgent: false,
    tags: [4],
    subtasks: [],
  },
  {
    id: 2,
    name: "Make bed",
    money: 0.25,
    permanent: true,
    repeatable: false,
    urgent: false,
    tags: [4],
    subtasks: [],
  },
  {
    id: 3,
    name: "Pick prescription up",
    money: 0.5,
    permanent: false,
    repeatable: false,
    urgent: false,
    tags: [2, 4],
    subtasks: [],
  },
  {
    id: 4,
    name: "Complete work on UI updates",
    money: 5,
    permanent: false,
    repeatable: false,
    urgent: true,
    tags: [3],
    subtasks: [3],
  },
  {
    id: 5,
    name: "Read one chapter",
    money: 0.5,
    permanent: true,
    repeatable: true,
    urgent: false,
    tags: [],
    subtasks: [2],
  },
  {
    id: 6,
    name: "Call Ali",
    money: 1,
    permanent: false,
    repeatable: false,
    urgent: false,
    tags: [],
    subtasks: [],
  },
  {
    id: 7,
    name: "Go to gym",
    money: 2,
    permanent: true,
    repeatable: false,
    urgent: false,
    tags: [2],
    subtasks: [1],
  },
];
